ami_id           = "ami-048e636f368eb3006"
instance_type    = "t2.micro"
project_name     = "shopping_app"
project_env      = "dev"
hosted_zone_name = "mrvishnu.shop"
#hosted_zone_id   = "Z03468102PAOAAQAZDLFL"
hostname = "redmi-dev"
