ami_id           = "ami-02e94b011299ef128"
instance_type    = "t2.micro"
project_name     = "shopping_app"
project_env      = "prod"
hosted_zone_name = "mrvishnu.shop"
#hosted_zone_id   = "Z03468102PAOAAQAZDLFL"
hostname = "redmi"
